<a href="https://colab.research.google.com/github/bloggernaresh4300-png/naresh_python/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
a = {'name':['virat','rohit','rishab'],'surname':['kohli','sharma','pant'],'century':[86,5,10],'iplteam':['rcb','mi','dc']}

In [ ]:
b = pd.DataFrame(a)

In [ ]:
b

     name surname  century iplteam
0   virat   kohli       86     rcb
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
type(b)

pandas.core.frame.DataFrame

In [ ]:
type(a)

dict

In [ ]:
b.head()

     name surname  century iplteam
0   virat   kohli       86     rcb
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
b.head(1)

    name surname  century iplteam
0  virat   kohli       86     rcb

In [ ]:
b.tail(2)

     name surname  century iplteam
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
b.shape

(3, 4)

In [ ]:
b.columns

Index(['name', 'surname', 'century', 'iplteam'], dtype='object')

In [ ]:
b.tail(2)

     name surname  century iplteam
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
b.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     3 non-null      object
 1   surname  3 non-null      object
 2   century  3 non-null      int64
 3   iplteam  3 non-null      object
dtypes: int64(1), object(3)
memory usage: 228.0+ bytes

In [ ]:
b.describe()

         century
count   3.000000
mean   33.666667
std    45.390895
min     5.000000
25%     7.500000
50%    10.000000
75%    48.000000
max    86.000000

In [ ]:
b['name']

0     virat
1     rohit
2    rishab
Name: name, dtype: object

In [ ]:
b['surname']

0     kohli
1    sharma
2      pant
Name: surname, dtype: object

In [ ]:
b[['name','surname']]

     name surname
0   virat   kohli
1   rohit  sharma
2  rishab    pant

In [ ]:
b[['surname','name','iplteam',]]

  surname    name iplteam
0   kohli   virat     rcb
1  sharma   rohit      mi
2    pant  rishab      dc

In [ ]:
#loc,iloc

In [ ]:
b.iloc[0,0]

'virat'

In [ ]:
b.iloc[0,1]

'kohli'

In [ ]:
b.iloc[0,2]

np.int64(86)

In [ ]:
b.iloc[0,3]

'rcb'

In [ ]:
b.iloc[1,2]

np.int64(5)

In [ ]:
b.iloc[1,0]

'rohit'

In [ ]:
b.iloc[2,3]

'dc'

In [ ]:
b.loc[0,'surname']

'kohli'

In [ ]:
b.loc[0,'iplteam']

'rcb'

In [ ]:
b.loc[0, ['iplteam', 'century']]

iplteam    rcb
century     86
Name: 0, dtype: object

In [ ]:
b.iloc[0,[2,3]]

century     86
iplteam    rcb
Name: 0, dtype: object

In [ ]:
b.iloc[[0,1],[2,3]]

   century iplteam
0       86     rcb
1        5      mi

In [ ]:
b.loc[[0,1],['century','iplteam']]

   century iplteam
0       86     rcb
1        5      mi

In [ ]:
b.iloc[[2,0],
 [0,1,2,3]]

     name surname  century iplteam
2  rishab    pant       10      dc
0   virat   kohli       86     rcb

In [ ]:
b.loc[[2,0],['name','surname','century','iplteam']]

     name surname  century iplteam
2  rishab    pant       10      dc
0   virat   kohli       86     rcb

In [ ]:
b.iloc[[2,0],]

     name surname  century iplteam
2  rishab    pant       10      dc
0   virat   kohli       86     rcb

In [ ]:
b.iloc[0:3:2,1:4:2]

  surname iplteam
0   kohli     rcb
2    pant      dc

In [ ]:
b

     name surname  century iplteam
0   virat   kohli       86     rcb
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
import sympy as sp

# Define the variables
x, y = sp.symbols('x y')

# Define the system of equations
eq1 = sp.Eq(x + y, 15)
eq2 = sp.Eq(x - y, 5)

# Solve the equations
solution = sp.solve((eq1, eq2), (x, y))
print(f"The solution is: x = {solution[x]}, y = {solution[y]}")

The solution is: x = 10, y = 5

In [ ]:
import pandas as pd

In [ ]:
#filtering a data frame

In [ ]:
b['century]+10

SyntaxError: unterminated string literal (detected at line 1) (4294280315.py, line 1)

In [ ]:
a = {'name':['virat','rohit','rishab'],'surname':['kohli','sharma','pant'],'century':[86,5,10],'iplteam':['rcb','mi','dc']}

In [ ]:
b = pd.DataFrame(a)

In [ ]:
b['century']+10

0    96
1    15
2    20
Name: century, dtype: int64

In [ ]:
b['century']%5==0

0    False
1     True
2     True
Name: century, dtype: bool

In [ ]:
b.loc[b['century']%5==0,['name','surname']]

     name surname
1   rohit  sharma
2  rishab    pant

In [ ]:
b.loc[b['century'] >= 50,]

    name surname  century iplteam
0  virat   kohli       86     rcb

In [ ]:
b.loc[b['century']<50,]

     name surname  century iplteam
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
b.loc[b['iplteam']=='rcb',]

    name surname  century iplteam
0  virat   kohli       86     rcb

In [ ]:
b.loc[b['iplteam']=='rcb',]

    name surname  century iplteam
0  virat   kohli       86     rcb

In [ ]:
#making new columns in data frame

In [ ]:
b

     name surname  century iplteam
0   virat   kohli       86     rcb
1   rohit  sharma        5      mi
2  rishab    pant       10      dc

In [ ]:
b['total_runs']=[1200,8000,5000]

In [ ]:
b

     name surname  century iplteam  total_runs
0   virat   kohli       86     rcb        1200
1   rohit  sharma        5      mi        8000
2  rishab    pant       10      dc        5000

In [ ]:
b.describe()

         century   total_runs
count   3.000000     3.000000
mean   33.666667  4733.333333
std    45.390895  3407.834112
min     5.000000  1200.000000
25%     7.500000  3100.000000
50%    10.000000  5000.000000
75%    48.000000  6500.000000
max    86.000000  8000.000000

In [ ]:
b.shape

(3, 5)

In [ ]:
b['country']='INDIA'

In [ ]:
b

     name surname  century iplteam  total_runs country
0   virat   kohli       86     rcb        1200   INDIA
1   rohit  sharma        5      mi        8000   INDIA
2  rishab    pant       10      dc        5000   INDIA

In [1]:
type(2)

int

In [3]:
type(100.98240)

float

In [6]:
a=100-50

In [7]:
a

50

In [ ]:
#/*+-
# ** - power
# // - quotient
# % - remainder